version: '3.9'

name: cms

services:
    php:
        container_name: ${COMPOSE_PROJECT_NAME}_php
        restart: unless-stopped
        build:
            args:
                WWWUSER: '${WWWUSER:-1000}'
                WWWGROUP: '${WWWGROUP:-1000}'
            context: .docker/php
            dockerfile: Dockerfile
            target: local-php
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '.:/var/www/app'
        networks:
            - default
            - proxy
        depends_on:
            - mariadb
            - redis
        expose:
            - 80
        labels:
            - traefik.enable=true
            - traefik.http.routers.${COMPOSE_PROJECT_NAME}_php.entrypoints=https
            - traefik.http.routers.${COMPOSE_PROJECT_NAME}_php.rule=Host(`${MAIN_DOMAIN:-cms.test}`) || Host(`${ADMIN_DOMAIN:-admin.cms.test}`)
            - traefik.http.routers.${COMPOSE_PROJECT_NAME}_php.tls=true
            - traefik.docker.network=proxy

    worker:
        container_name: ${COMPOSE_PROJECT_NAME}_worker
        restart: unless-stopped
        build:
            args:
                WWWUSER: '${WWWUSER:-1000}'
                WWWGROUP: '${WWWGROUP:-1000}'
            context: .docker/php
            dockerfile: Dockerfile
            target: local-worker
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '.:/var/www/app'
        networks:
            - default
        depends_on:
            - mariadb
            - redis

    node:
        container_name: ${COMPOSE_PROJECT_NAME}_node
        restart: unless-stopped
        build:
            context: ./.docker/node
            dockerfile: Dockerfile
            target: local-node
        volumes:
            - ./:/var/www/app
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - '${VITE_FORWARDED_PORT:-5173}:5173'
        networks:
            - default
            - proxy
        labels:
            - traefik.enable=true
            - traefik.http.routers.${COMPOSE_PROJECT_NAME}_node.entrypoints=https
            - traefik.http.routers.${COMPOSE_PROJECT_NAME}_node.rule=Host(`${VITE_DOMAIN:-vite.cms.test}`)
            - traefik.http.services.${COMPOSE_PROJECT_NAME}_node.loadbalancer.server.port=5173
            - traefik.http.routers.${COMPOSE_PROJECT_NAME}_node.tls=true
            - traefik.docker.network=proxy

    mariadb:
        container_name: ${COMPOSE_PROJECT_NAME}_mariadb
        restart: unless-stopped
        image: mariadb:10
        volumes:
            - mariadb:/var/lib/mysql
        ports:
            - ${DB_APP_FORWARDED_PORT:-3308}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_APP_ROOT_PASSWORD:-root}
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: ${DB_APP_DATABASE}
            MYSQL_USER: ${DB_APP_USERNAME}
            MYSQL_PASSWORD: ${DB_APP_PASSWORD}
        networks:
            - default
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_ROOT_PASSWORD:-root}" ]
            retries: 3
            timeout: 5s

    redis:
        container_name: ${COMPOSE_PROJECT_NAME}_redis
        restart: unless-stopped
        image: 'redis:alpine'
        ports:
            - '${REDIS_FORWARDED_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        networks:
            - default
        healthcheck:
            test: [ "CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    soketi:
        container_name: ${COMPOSE_PROJECT_NAME}_soketi
        restart: unless-stopped
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        environment:
            SOKETI_DEBUG: '${SOKETI_DEBUG:-1}'
            SOKETI_METRICS_SERVER_PORT: '9601'
            SOKETI_DEFAULT_APP_ID: '${PUSHER_APP_ID}'
            SOKETI_DEFAULT_APP_KEY: '${PUSHER_APP_KEY}'
            SOKETI_DEFAULT_APP_SECRET: '${PUSHER_APP_SECRET}'
        ports:
            - '${PUSHER_FORWARDED_PORT:-6001}:6001'
            - '${PUSHER_METRICS_FORWARDED_PORT:-9601}:9601'
        networks:
            - default
            - proxy
        labels:
            - traefik.enable=true
            - traefik.http.routers.${COMPOSE_PROJECT_NAME}_soketi.entrypoints=https
            - traefik.http.routers.${COMPOSE_PROJECT_NAME}_soketi.rule=Host(`${WS_DOMAIN:-ws.cms.test}`)
            - traefik.http.services.${COMPOSE_PROJECT_NAME}_soketi.loadbalancer.server.port=6001
            - traefik.http.routers.${COMPOSE_PROJECT_NAME}_soketi.tls=true
            - traefik.docker.network=proxy

networks:
    default:
        driver: bridge
        name: ${COMPOSE_PROJECT_NAME}
    proxy:
        external: true

volumes:
    mariadb:
        driver: local
    redis:
        driver: local
